### ISSUE TITLE
App size suddenly doubled. Malware concern.

### ISSUE THREAD

**Issue by a-raccoon** [tengusw/share_to_clipboard#10]
The size of this app suddenly more than doubled in size, from 853 KB to over 2 MB, on the F-Droid market.  Cannot locate explanation of why.  Natural concern over presence of malware is raised.

**Comment by a-raccoon** [comment]
Malware confirmed, by presence of hacker tag of a Soviet communist with a penis-nose artwork resources introduced to app.

https://github.com/tengusw/share_to_clipboard/commit/f508ee82ed5f62a6ed9e38a49642d47a8e5a0159#diff-9e63ece2d2ed71ed33412cd33ac192b1

**Comment by mvdan** [comment]
Seriously?

**Comment by krt16s** [comment]
Not a "hacker tag", but image of Tengu, see https://upload.wikimedia.org/wikipedia/commons/1/1d/Tengu.jpg ...

**Comment by tasn** [comment]
@a-raccoon, thank you for raising this issue. I'm glad we have people verifying nothing bad sneaks in.
However, I have to disagree with your assessment on a few levels.
First of all, as @krt16s said (thanks for replying to him), it is not a communist tag, but our app building logo.
Second of all, and more relevant to the issue, it's not the reason for the added size.

We've had a lot of users confused by the lack of a launcher for this app. Many calling it "malware" on the play store because of it. We've thus decided to add a basic activity that explains a bit about the app, and in the process, we also added our logo, and a link to the our other apps. As part of the process, we had to add an activity, and to style it nicely for newer android devices without raising our Android version requirements, we had to include the android app comparability library, which is, as you've noticed, quite big. We'll take a look into removing this dependency, hopefully it wouldn't be too hard. If you have the time, and are able to do so, a patch to implement that would be appreciated. Otherwise, we'll try to get to it as soon as possible.

Thanks again, for being a watchdog. This is what keeps us all safe.

**Comment by a-raccoon** [comment]
Thanks for the follow-up.  I do suspect, however, that a large portion of the size bloat is from your "logo" resource appearing a half dozen times in multiple resolutions from tiny to huge.  You might consider removing the excessive glam to feel more professional.

ALSO, take a look at whatever Clip Stack is doing.  They have a fully featured user interface and perform advanced clipboard monitoring and logging, at a third less the size of your app.

Honestly, I still don't understand or agree with your reasoning.  I've not heard of the complaint you've made, and in contrast, people are more leary of inexplicably large apps versus apps that are small and scrappy and don't have throbbing communist penis noses. :p

**Comment by mvdan** [comment]
> a large portion of the size bloat is from your "logo" resource appearing a half dozen times in multiple resolutions from tiny to huge. You might consider removing the excessive glam to feel more professional.

You do know how drawables in Android work, right?

**Comment by tasn** [comment]
@a-raccoon, clip stack is android 4.0+, we are 2.2+. They are probably also using the app compat library (haven't checked), but because of the different version requirements, a lot less of it is actually included, and thus the resulting size is smaller. We still have users using Android < 4.0, so it doesn't make sense for us to not support them just for the sake of reducing the app size.

It is not the logo. Following your initial complaint we recompiled the app without the logo to verify, and indeed, that is not the culprit. We already faced the size issue when we first uploaded the app, and it turned out to be the app compat lib. As previously mentioned, we'll try to get rid of it, but only if it doesn't harm the aesthetics.

As @mvdan mentioned, this is how Android works. It's needed for a more efficient multi-DPI support.

As for the malware argument: we've got a lot of people calling this app a virus on Google play comments, and on the other hand I'm not aware of anyone looking at app sizes when installing apps. With that being said, and as previously mentioned, we'll take a look into that.

**Comment by a-raccoon** [comment]
Alright, I concede to your explanation and assessment.  If I may, though, interject one more opinion:  If you are genuinely providing backward compatibility for Android 2.2 devices, do consider that many of those devices only come with 1 to 4 gigs of app storage, maybe even 512 MB, while 4.x devices came with 8 and 16 gigs.  Making your 2.2 apps twice as large isn't doing 2.2 users very much favor.

Yiou might consider forking off 2.x and 4.x as independent projects if it means bundling so many libraries that it accounts for 50 or 75% of your code.

**Comment by tasn** [comment]
Fair point, though let's put things in proportions, we are talking about a 1.5MB size decrease here. In comparison, Chrome for Android is 53 MB, Twitter is 20 MB, and an average picture you take with your phone camera is at least 500 KB, so we are talking about the equivalent of 3 pictures. Hopefully it'll be solved if (when?) we manage to get rid of the app compat library dep.

The two versions as independent projects is a pain in the ass. Some app devs do it, but I'm not willing to go down that path.

Thanks again for raising your concerns.

**Comment by tasn** [comment]
Fixed in v1.4.0, though the hacker tag remains. ;P

Thanks again for reporting.
